name: Keep Alive
on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Health Endpoint
        run: curl -I https://flux-vcz7.onrender.com/check
